image: gitlab.ee.playtech.corp:4567/po/mws-ci-tests:latest

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/
    - portlets/mobile-portlet/docroot/js/components/
    - npm_cache/

before_script:
  - export npm_config_cache="npm_cache"
  - export npm_config_registry="http://ua-mws-nexus01.ee.playtech.corp/nexus/content/repositories/npmjs/"
  - npm install --quiet

fetest:
  script:
    - npm run-script gulp
