image: registry.middle-of-nowhere.name:443/docker-images/npm-packager:latest

stages:
  - build
  - publish

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules/
  untracked: false

before_script:
    - npm i

build:
  stage: build
  script:
    - npx gulp
    - npx gulp test

publish:
  before_script:
    - 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc'
  stage: publish
  script:
    - npm publish
  only:
    refs:
      - tags

